### ISSUE TITLE
ReplicaSet reports invalid container name when failing on resources

### ISSUE THREAD

**Issue by Mikulas** [clusterise/rollout-status#4]
Message:

>   ReplicaSet "demo-tst-main-5d8fdf4678" failed to create pods: pods "demo-tst-main-5d8fdf4678-bwp94" is forbidden: failed quota: **main**: must specify cpu,memory

Expected message

>   ReplicaSet "demo-tst-main-5d8fdf4678" failed to create pods: pods "demo-tst-main-5d8fdf4678-bwp94" is forbidden: failed quota: **fluentd**: must specify cpu,memory

Resources are not missing on `main` container but on the sidecar.

<details>

## Payload

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cc.mgit.cz/cluster: tst
    prometheus.io/port: "80"
    prometheus.io/scrape: "false"
  creationTimestamp: null
  labels:
    app: demo
    cc.mgit.cz/prune-key: demo-tst
    component: app
    environment: test
    service: cc-demo
    stage: tst
    team: cc
  name: demo-tst-main
  namespace: cc
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      cc.mgit.cz/prune-key: demo-tst
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cc.mgit.cz/cluster: tst
        prometheus.io/port: "80"
        prometheus.io/scrape: "false"
      creationTimestamp: null
      labels:
        app: demo
        cc.mgit.cz/prune-key: demo-tst
        component: app
        environment: test
        service: cc-demo
        stage: tst
        team: cc
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: dummy-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: key
              name: demo-tst-vault-db-password
        image: registry.mallgroup.com/cc/demo:invalid-tag
        name: main
        ports:
        - containerPort: 80
          name: main
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /sidecar/counter
          name: sidecar-counter
        - mountPath: /var/log/app
          name: log-storage
          subPath: var/log/app
      - command:
        - sh
        - -c
        - while true; do date >> /sidecar/counter/output.txt; sleep 1; done
        env:
        - name: DB_NAME
          value: dummy-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: key
              name: demo-tst-vault-db-password
        image: alpine:3.11
        name: counter
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /sidecar/counter
          name: sidecar-counter
        - mountPath: /var/log/app
          name: log-storage
          subPath: var/log/app
      - env:
        - name: FLUENT_REMOTE_HOST
          value: logs.mgit.cz
        - name: FLUENT_REMOTE_PORT
          value: "5046"
        - name: FLUENTD_ARGS
          value: -c /fluentd/etc/custom.conf
        - name: CLUSTER_NAME
          value: tst
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: META_TEAM
          value: cc
        - name: META_SERVICE
          value: cc-demo
        - name: META_COMPONENT
          value: app
        - name: META_ENV
          value: test
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        name: fluentd
        resources: {}
        volumeMounts:
        - mountPath: /fluentd/etc/custom.conf
          name: config-volume
          readOnly: true
          subPath: custom.conf
        - mountPath: /var/log/app
          name: log-storage
          subPath: var/log/app
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: sidecar-counter
      - emptyDir: {}
        name: log-storage
      - configMap:
          name: demo-tst-main-fluentd
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-meta-component: app
    consul.hashicorp.com/service-meta-environment: test
    consul.hashicorp.com/service-meta-myKey: myValue
    consul.hashicorp.com/service-meta-service: cc-demo
    consul.hashicorp.com/service-meta-team: cc
    consul.hashicorp.com/service-name: cc-demo-custom-consul-name
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-tags: http,myTag1,myTag2
    prometheus.io/scrape: "false"
  creationTimestamp: null
  labels:
    app: demo
    cc.mgit.cz/prune-key: demo-tst
    component: app
    environment: test
    service: cc-demo
    stage: tst
    team: cc
  name: demo-tst-main
  namespace: cc
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    cc.mgit.cz/prune-key: demo-tst
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: koudingspawn.de/v1
kind: VaultSecret
metadata:
  annotations:
    prometheus.io/scrape: "false"
  creationTimestamp: null
  labels:
    app: demo
    cc.mgit.cz/prune-key: demo-tst
    component: app
    environment: test
    service: cc-demo
    stage: tst
    team: cc
  name: demo-tst-vault-db-password
  namespace: cc
spec:
  path: secret/cc/demo/document
  type: KEYVALUE
---
apiVersion: v1
data:
  custom.conf: "<source>\n  @type tail\n  @id in_tail_app_logs\n  path /var/log/app/demo.txt\n
    \ pos_file /var/log/app/fluentd-app.log.pos\n  tag app.*\n  read_from_head true\n
    \ path_key log_path\n  <parse>\n    @type regexp\n    expression /^\\[(?<logtime>[^\\]]*)\\]
    (?<random1>[^ ]*) (?<kw1>[^ ]*) (?<kw2>[^ ]*) (?<random2>[^ ]*)$/\n    time_key
    logtime\n    time_format %Y-%m-%dT%H:%M:%SZ\n  </parse>\n</source>\n\n<filter
    **>\n  @type record_transformer\n  enable_ruby true\n  auto_typecast true\n  <record>\n
    \   log_path \"${record['log_path']}\"\n    kubernetes ${{ \"cluster\" => \"#{ENV['CLUSTER_NAME']}\",
    \"host\" => \"#{ENV['NODE_NAME']}\", \"pod_name\" => \"#{ENV['POD_NAME']}\", \"namespace_name\"
    => \"#{ENV['POD_NAMESPACE']}\" }}\n\tfields ${{ \"kind\" => \"log\", \"mall_metadata\"
    => { \"team\" => \"#{ENV['META_TEAM']}\", \"service\" => \"#{ENV['META_SERVICE']}\",
    \"component\" => \"#{ENV['META_COMPONENT']}\", \"env\" => \"#{ENV['META_ENV']}\"
    } }}\n\ttags [\"json\"]\n  </record>\n</filter>\n<match **>\n  @type forward\n
    \ @id out_logstash\n  @log_level debug\n  time_as_integer true\n  send_timeout
    60s\n  recover_wait 10s\n  heartbeat_type none\n  phi_threshold 16\n  hard_timeout
    60s\n  <server>\n    host \"#{ENV['FLUENT_REMOTE_HOST']}\"\n    port \"#{ENV['FLUENT_REMOTE_PORT']}\"\n
    \   weight 60\n  </server>\n</match>\n"
kind: ConfigMap
metadata:
  annotations:
    prometheus.io/scrape: "false"
  creationTimestamp: null
  labels:
    app: demo
    cc.mgit.cz/prune-key: demo-tst
    component: app
    environment: test
    service: cc-demo
    stage: tst
    team: cc
  name: demo-tst-main-fluentd
  namespace: cc
---
apiVersion: cronjobber.hidde.co/v1alpha1
kind: TZCronJob
metadata:
  annotations:
    prometheus.io/scrape: "false"
  creationTimestamp: null
  labels:
    app: demo
    cc.mgit.cz/prune-key: demo-tst
    component: app
    environment: test
    service: cc-demo
    stage: tst
    team: cc
  name: demo-tst-main
  namespace: cc
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "false"
          creationTimestamp: null
          labels:
            app: demo
            cc.mgit.cz/prune-key: demo-tst
            component: app
            environment: test
            service: cc-demo
            stage: tst
            team: cc
        spec:
          containers:
          - command:
            - echo
            - This is a newsletter
            env:
            - name: DB_NAME
              value: dummy-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: key
                  name: demo-tst-vault-db-password
            image: registry.mallgroup.com/cc/demo:2f7d5654a020fa87369130449445618957f92396
            name: main
            resources:
              limits:
                cpu: 100m
                memory: 50Mi
              requests:
                cpu: 100m
                memory: 50Mi
          restartPolicy: OnFailure
  schedule: 0 */3 * * *
  timezone: Europe/Prague
status: {}
---
apiVersion: koudingspawn.de/v1
kind: VaultSecret
metadata:
  annotations:
    prometheus.io/scrape: "false"
  creationTimestamp: null
  labels:
    app: demo
    cc.mgit.cz/prune-key: demo-tst
    component: app
    environment: test
    service: cc-demo
    stage: tst
    team: cc
  name: demo-tst-vault-db-password
  namespace: cc
spec:
  path: secret/cc/demo/document
  type: KEYVALUE
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app: demo
    cc.mgit.cz/prune-key: prometheus-rules
    component: app
    environment: test
    prometheus: main
    role: alert-rules
    service: cc-demo
    stage: tst
    team: cc
  name: demo-tst-rules
  namespace: system-monitoring
spec:
  groups:
  - interval: 60s
    name: tst
    rules:
    - expr: sum(http_inprogress_requests) by (job)
      labels:
        component: app
        environment: test
        service: cc-demo
        team: cc
      record: job:http_inprogress_requests:sum
    - alert: HighRequestLatency
      annotations:
        summary: High request latency
      expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
      for: 10m
      labels:
        component: app
        environment: test
        service: cc-demo
        severity: page
        team: cc
```

</details>
